@extends('layouts.teacher')

@php
    $scope = $requiredScope ?? 'division';
    $isDivision = $scope === 'division';
    $pageTitle = $dashboardTitle ?? ($isDivision ? 'TB Responsable type d’enseignement' : 'TB Responsable département / filière');
@endphp

@section('title', $pageTitle)
@section('page_title', $pageTitle)
@section('page_subtitle', $isDivision ? 'Suivi des départements, enseignants, cours, TD et questions rattachés à un type d’enseignement.' : 'Suivi des enseignants, classes, matières, cours, TD et questions rattachés à un département ou une filière.')

@section('content')
@php
    $schemaReady = \Illuminate\Support\Facades\Schema::hasTable('pedagogical_responsibilities')
        && \Illuminate\Support\Facades\Schema::hasTable('teaching_divisions')
        && \Illuminate\Support\Facades\Schema::hasTable('teaching_departments')
        && \Illuminate\Support\Facades\Schema::hasTable('pedagogical_supervision_notes');
    $responsibilities = collect(); $responsibility = null; $area = null; $departments = collect(); $subjects = collect(); $subjectIds = collect(); $classIds = collect();
    $stats = ['teachers'=>0,'students'=>0,'departments'=>0,'classes'=>0,'subjects'=>0,'courses_published'=>0,'courses_draft'=>0,'td_published'=>0,'questions_open'=>0,'notes_open'=>0];
    $teachers=collect(); $classes=collect(); $courses=collect(); $tdSets=collect(); $questions=collect(); $notes=collect();
    $statusClass = fn($status) => match($status){'published','active','open'=>'rz-badge--success','draft','pending','programmed'=>'rz-badge--warning','urgent'=>'rz-badge--danger',default=>'rz-badge--neutral'};
    $labelStatus = fn($status) => match($status){'published'=>'Publié','draft'=>'Brouillon','open'=>'Ouverte','active'=>'Actif','urgent'=>'Urgent','warning'=>'Attention','info'=>'Info',default=>$status ?: '—'};
    if ($schemaReady) {
        $responsibilities = \Illuminate\Support\Facades\DB::table('pedagogical_responsibilities as pr')->leftJoin('teaching_divisions as div','div.id','=','pr.teaching_division_id')->leftJoin('teaching_departments as dep','dep.id','=','pr.teaching_department_id')->where('pr.user_id',auth()->id())->where('pr.is_active',true)->where('pr.scope_type',$scope)->select('pr.*','div.name as division_name','dep.name as department_name')->orderByDesc('pr.id')->get();
        $responsibility = $responsibilities->firstWhere('id',(int)request('responsibility')) ?: $responsibilities->first();
        if ($responsibility) {
            if ($isDivision) { $area = \Illuminate\Support\Facades\DB::table('teaching_divisions')->where('id',$responsibility->teaching_division_id)->first(); $departments = \Illuminate\Support\Facades\DB::table('teaching_departments')->where('teaching_division_id',$responsibility->teaching_division_id)->where('is_active',true)->get(); }
            else { $department = \Illuminate\Support\Facades\DB::table('teaching_departments')->where('id',$responsibility->teaching_department_id)->first(); $area = $department; $departments = $department ? collect([$department]) : collect(); }
            $subjectIds = $departments->pluck('subject_id')->filter()->unique()->values(); $classIds = $departments->pluck('school_class_id')->filter()->unique()->values(); $stats['subjects']=$subjectIds->count(); $stats['departments']=$departments->count(); $stats['classes']=$classIds->count();
            $applyScope = function($query,string $table,string $alias='') use($subjectIds,$classIds){$p=$alias!==''?$alias.'.':'';$hs=$subjectIds->isNotEmpty()&&\Illuminate\Support\Facades\Schema::hasColumn($table,'subject_id');$hc=$classIds->isNotEmpty()&&\Illuminate\Support\Facades\Schema::hasColumn($table,'school_class_id');if(!$hs&&!$hc)return $query;return $query->where(function($q)use($hs,$hc,$p,$subjectIds,$classIds){if($hs)$q->orWhereIn($p.'subject_id',$subjectIds->all());if($hc)$q->orWhereIn($p.'school_class_id',$classIds->all());});};
            if(\Illuminate\Support\Facades\Schema::hasTable('teacher_assignments')){$q=\Illuminate\Support\Facades\DB::table('teacher_assignments as ta')->where('ta.is_active',true);$stats['teachers']=$applyScope($q,'teacher_assignments','ta')->distinct()->count('ta.teacher_id');}
            if(\Illuminate\Support\Facades\Schema::hasTable('student_profiles')){$q=\Illuminate\Support\Facades\DB::table('student_profiles');if($classIds->isNotEmpty()&&\Illuminate\Support\Facades\Schema::hasColumn('student_profiles','school_class_id'))$q->whereIn('school_class_id',$classIds->all());$stats['students']=$q->count();}
            if(\Illuminate\Support\Facades\Schema::hasTable('subjects')&&$subjectIds->isNotEmpty()){$subjects=\Illuminate\Support\Facades\DB::table('subjects')->whereIn('id',$subjectIds->all())->get();}
            if(\Illuminate\Support\Facades\Schema::hasTable('school_classes')&&$classIds->isNotEmpty()){$classes=\Illuminate\Support\Facades\DB::table('school_classes')->whereIn('id',$classIds->all())->get();}
            if(\Illuminate\Support\Facades\Schema::hasTable('courses')){$base=$applyScope(\Illuminate\Support\Facades\DB::table('courses'),'courses');$stats['courses_published']=(clone $base)->where('status','published')->count();$stats['courses_draft']=(clone $base)->where('status','draft')->count();$courses=$applyScope(\Illuminate\Support\Facades\DB::table('courses as item')->leftJoin('school_classes as cl','cl.id','=','item.school_class_id')->leftJoin('subjects as s','s.id','=','item.subject_id')->select('item.id','item.title','item.status','cl.name as class_name','s.name as subject_name')->orderByDesc('item.id')->limit(8),'courses','item')->get();}
            if(\Illuminate\Support\Facades\Schema::hasTable('td_sets')){$base=$applyScope(\Illuminate\Support\Facades\DB::table('td_sets'),'td_sets');$stats['td_published']=(clone $base)->where('status','published')->count();$tdSets=$applyScope(\Illuminate\Support\Facades\DB::table('td_sets as item')->leftJoin('school_classes as cl','cl.id','=','item.school_class_id')->leftJoin('subjects as s','s.id','=','item.subject_id')->select('item.id','item.title','item.status','cl.name as class_name','s.name as subject_name')->orderByDesc('item.id')->limit(8),'td_sets','item')->get();}
            $notes=\Illuminate\Support\Facades\DB::table('pedagogical_supervision_notes as n')->leftJoin('users as u','u.id','=','n.target_user_id')->when($isDivision,fn($q)=>$q->where('n.teaching_division_id',$responsibility->teaching_division_id))->when(!$isDivision,fn($q)=>$q->where('n.teaching_department_id',$responsibility->teaching_department_id))->select('n.*','u.full_name','u.name','u.username')->orderByDesc('n.id')->limit(8)->get();$stats['notes_open']=$notes->where('status','open')->count();
        }
    }
@endphp
<style>.rz-wrap{display:grid;gap:18px}.rz-top{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;background:#fff;border:1px solid #e2e8f0;border-radius:24px;padding:18px;box-shadow:0 16px 40px rgba(15,23,42,.06)}.rz-top h2{margin:0;color:#0f172a;font-size:clamp(1.8rem,4vw,2.8rem)}.rz-top h3{margin:4px 0 8px;color:#075ee8;font-size:1.35rem}.rz-actions{display:flex;gap:10px;flex-wrap:wrap}.rz-btn{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:0 14px;border-radius:14px;border:1px solid #dbeafe;background:#fff;color:#0f172a;font-weight:900;text-decoration:none}.rz-btn--primary{background:#0f2a69;color:#fff;border-color:#0f2a69}.rz-btn--success{background:#16a34a;color:#fff;border-color:#16a34a}.rz-reserved{display:inline-flex;gap:8px;padding:10px 14px;border-radius:14px;background:#eff6ff;border:1px solid #bfdbfe;color:#1d4ed8;font-weight:900;margin-bottom:10px}.rz-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.rz-card,.rz-panel,.rz-alerts,.rz-note-form{background:#fff;border:1px solid #e2e8f0;border-radius:20px;padding:16px;box-shadow:0 12px 28px rgba(15,23,42,.05)}.rz-card{display:flex;gap:12px;align-items:center}.rz-ico{width:50px;height:50px;border-radius:16px;display:grid;place-items:center;font-size:24px;background:#eef2ff}.rz-card span{display:block;color:#64748b;font-weight:800}.rz-card strong{font-size:1.9rem;color:#0f172a}.rz-panels{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.rz-panel__head{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.rz-panel__head a{color:#2563eb;font-weight:900;text-decoration:none}.rz-row{border:1px solid #e5e7eb;background:#f8fafc;border-radius:14px;padding:10px;margin-bottom:9px}.rz-badge{display:inline-flex;border-radius:999px;padding:5px 9px;font-size:12px;font-weight:900}.rz-badge--success{background:#dcfce7;color:#166534}.rz-badge--warning{background:#fff7ed;color:#c2410c}.rz-badge--danger{background:#ffe4e6;color:#be123c}.rz-badge--neutral{background:#eef2ff;color:#3730a3}.rz-empty{padding:16px;border-radius:16px;background:#f8fafc;color:#64748b}.rz-note-form form{display:grid;grid-template-columns:2fr 1fr auto;gap:10px}.rz-note-form input,.rz-note-form select{border:1px solid #cbd5e1;border-radius:12px;padding:10px}.rz-footer{display:flex;justify-content:space-between;color:#64748b;font-weight:800}@media(max-width:1100px){.rz-grid,.rz-panels{grid-template-columns:1fr 1fr}.rz-top{display:grid}}@media(max-width:720px){.rz-grid,.rz-panels{grid-template-columns:1fr}.rz-btn,.rz-actions{width:100%}.rz-note-form form{grid-template-columns:1fr}}</style>
<div class="rz-wrap">
@if(!$schemaReady)<section class="rz-top"><div><h2>Migration nécessaire</h2><p>Les tables de supervision ne sont pas encore installées.</p></div></section>
@elseif(!$responsibility)<section class="rz-top"><div><h2>Accès réservé</h2><p>Ce tableau de bord est réservé aux responsables ayant une responsabilité active.</p></div><div class="rz-actions"><a class="rz-btn" href="{{ route('teacher.dashboard') }}">Retour</a></div></section>
@else
<section class="rz-top"><div><div class="rz-reserved">🔒 Espace réservé : {{ $responsibility->role_title }}</div><h2>{{ $pageTitle }}</h2><h3>{{ $area->name ?? ($isDivision ? 'Type d’enseignement' : 'Département / filière') }}</h3><p>{{ $isDivision ? 'Vous supervisez les départements, enseignants, cours, TD et relances.' : 'Vous gérez les matières et classes liées à votre département dans un espace séparé, sans passer par la page admin.' }}</p></div><div class="rz-actions"><a class="rz-btn" href="{{ route('teacher.dashboard') }}">← Retour</a>@if(!$isDivision && \Illuminate\Support\Facades\Route::has('department.classes.index'))<a class="rz-btn rz-btn--primary" href="{{ route('department.classes.index') }}">Gérer les classes</a>@endif @if(!$isDivision && \Illuminate\Support\Facades\Route::has('department.subjects.index'))<a class="rz-btn rz-btn--primary" href="{{ route('department.subjects.index') }}">Gérer les matières</a>@endif @if(\Illuminate\Support\Facades\Route::has('responsibilities.followups.index'))<a class="rz-btn" href="{{ route('responsibilities.followups.index') }}">Suivi pédagogique</a>@endif <a class="rz-btn rz-btn--success" href="#note-suivi">+ Créer une alerte</a></div></section>
<section class="rz-grid"><article class="rz-card"><div class="rz-ico">👥</div><div><span>Enseignants</span><strong>{{ $stats['teachers'] }}</strong></div></article><article class="rz-card"><div class="rz-ico">🎓</div><div><span>Élèves concernés</span><strong>{{ $stats['students'] }}</strong></div></article><article class="rz-card"><div class="rz-ico">🏫</div><div><span>{{ $isDivision ? 'Départements' : 'Classes liées' }}</span><strong>{{ $isDivision ? $stats['departments'] : $stats['classes'] }}</strong></div></article><article class="rz-card"><div class="rz-ico">📘</div><div><span>{{ !$isDivision ? 'Matières liées' : 'Cours publiés' }}</span><strong>{{ !$isDivision ? $stats['subjects'] : $stats['courses_published'] }}</strong></div></article><article class="rz-card"><div class="rz-ico">📗</div><div><span>Cours publiés</span><strong>{{ $stats['courses_published'] }}</strong></div></article><article class="rz-card"><div class="rz-ico">📝</div><div><span>Cours brouillons</span><strong>{{ $stats['courses_draft'] }}</strong></div></article><article class="rz-card"><div class="rz-ico">📄</div><div><span>TD publiés</span><strong>{{ $stats['td_published'] }}</strong></div></article><article class="rz-card"><div class="rz-ico">📋</div><div><span>Alertes ouvertes</span><strong>{{ $stats['notes_open'] }}</strong></div></article></section>
<div class="rz-panels"><section class="rz-panel"><div class="rz-panel__head"><h3>Classes concernées</h3>@if(!$isDivision && \Illuminate\Support\Facades\Route::has('department.classes.index'))<a href="{{ route('department.classes.index') }}">Gérer</a>@endif</div>@forelse($classes as $class)<div class="rz-row"><strong>{{ $class->name }}</strong><br><span>{{ $class->level ?? 'Niveau non précisé' }}</span></div>@empty<div class="rz-empty">Aucune classe liée directement.</div>@endforelse</section>@if(!$isDivision)<section class="rz-panel"><div class="rz-panel__head"><h3>Matières du département</h3>@if(\Illuminate\Support\Facades\Route::has('department.subjects.index'))<a href="{{ route('department.subjects.index') }}">Gérer</a>@endif</div>@forelse($subjects as $subject)<div class="rz-row"><strong>{{ $subject->name }}</strong><br><span>Liée au département</span></div>@empty<div class="rz-empty">Aucune matière liée directement au département.</div>@endforelse</section>@endif<section class="rz-panel"><div class="rz-panel__head"><h3>Suivi / relances</h3>@if(\Illuminate\Support\Facades\Route::has('responsibilities.followups.index'))<a href="{{ route('responsibilities.followups.index') }}">Voir tout</a>@endif</div>@forelse($notes as $note)<div class="rz-row"><strong>{{ $note->title }}</strong><br><small>{{ $labelStatus($note->status) }}</small></div>@empty<div class="rz-empty">Aucune alerte.</div>@endforelse</section><section class="rz-panel"><div class="rz-panel__head"><h3>Cours récents</h3></div>@forelse($courses as $course)<div class="rz-row"><strong>{{ $course->title }}</strong><br><span>{{ $course->class_name ?? '-' }} · {{ $course->subject_name ?? '-' }}</span></div>@empty<div class="rz-empty">Aucun cours.</div>@endforelse</section><section class="rz-panel"><div class="rz-panel__head"><h3>TD récents</h3></div>@forelse($tdSets as $td)<div class="rz-row"><strong>{{ $td->title }}</strong><br><span>{{ $td->class_name ?? '-' }} · {{ $td->subject_name ?? '-' }}</span></div>@empty<div class="rz-empty">Aucun TD.</div>@endforelse</section></div>
<section class="rz-note-form" id="note-suivi"><h3>Créer une alerte rapide</h3><form method="POST" action="{{ route('supervision.notes.store') }}">@csrf<input type="hidden" name="responsibility_id" value="{{ $responsibility->id }}"><input name="title" required placeholder="Exemple : TD en attente de publication"><select name="severity"><option value="info">Info</option><option value="warning">Attention</option><option value="urgent">Urgent</option></select><button type="submit" class="rz-btn rz-btn--success">Enregistrer</button></form></section>
<div class="rz-footer"><span>Dernière mise à jour : {{ now()->format('d/m/Y H:i') }}</span><span>Une solution Cabrel Tech.</span></div>
@endif
</div>
@endsection
